- type: job
  id: CentralCommandOfficial
  name: "Central Command Official"
  description: "Either you're the captain's boss or you're some random intern. Either way, expect a metric fuckton of paperwork."
  playTimeTracker: JobCentralCommandOfficial
  setPreference: false
  startingGear: CentcomGear
  icon: "JobIconNanotrasen"
  supervisors: "mostly yourself, depending on your role"
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 10
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: CentcomGear
  subGear:
  - CentcomPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    back: ClothingBackpackSatchelNanorep
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatCentcom
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterArmorBasic
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: WeaponPistolN1984
    pocket1: EncryptionKeyDeathsquad
    pocket2: EncryptionKeyERT

- type: startingGear
  id: CentcomPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitCentcomOfficial
    head: ClothingHeadEnvirohelmCentcomOfficial
    gloves: ClothingHandsGlovesEnviroglovesBlack
